openapi: 3.0.0
info:
  title: Connections
  version: '1.0'
  description: Describes endpoints for managing DB connections
  contact:
    name: Michal Kasal
  license:
    url: 'https://creativecommons.org/licenses/by-nc-nd/4.0/'
    name: CC BY-NC-ND 4.0
servers:
  - url: 'localhost:8080'
components:
  schemas:
    ConnectionDTO:
      title: ConnectionDTO
      type: object
      description: Describes database connection object
      x-examples:
        first_example:
          id: 476
          name: EXAMPLE CRM PROD
          hostname: example.com
          port: 12345
          databaseName: crmdb
          username: admin
          password: pa$$word
      properties:
        id:
          type: integer
          format: int64
          description: ID of resource
        name:
          type: string
          example: Core banking system - production
          minLength: 3
          maxLength: 255
          description: Name of stored DB connection
        hostname:
          type: string
          format: hostname
          example: example.com
          description: Hostname or IP address
        port:
          type: integer
          description: Port number where DB accepts connections
          minimum: 1
          maximum: 65535
          example: 5431
        databaseName:
          type: string
          maxLength: 63
          minLength: 1
        username:
          type: string
          maxLength: 63
          minLength: 1
        password:
          type: string
          format: password
      required:
        - name
        - hostname
        - port
        - databaseName
        - username
        - password
    ApiExceptionDTO:
      title: ApiErrorDTO
      type: object
      description: Represents error that occured during processing of request
      properties:
        message:
          type: string
        errors:
          type: array
          items:
            type: string
    SchemaDTO:
      description: Represents information about database schema
      type: object
      properties:
        catalog_name:
          type: string
          minLength: 1
        schema_name:
          type: string
          minLength: 1
        schema_owner:
          type: string
          minLength: 1
        default_character_set_catalog:
          type: string
        default_character_set_schema:
          type: string
        default_character_set_name:
          type: string
        sql_path:
          type: string
      required:
        - catalog_name
        - schema_name
        - schema_owner
      title: SchemaDTO
      x-examples:
        example-1:
          catalog_name: string
          schema_name: string
          schema_owner: string
          default_character_set_catalog: string
          default_character_set_schema: string
          default_character_set_name: string
          sql_path: string
      x-tags:
        - schema
    TableDTO:
      description: Represents info about database table
      type: object
      title: TableDTO
      properties:
        table_catalog:
          type: string
          minLength: 1
        table_schema:
          type: string
          minLength: 1
        table_name:
          type: string
          minLength: 1
        table_type:
          type: string
          minLength: 1
        self_referencing_column_name:
          type: string
        reference_generation:
          type: string
        user_defined_type_catalog:
          type: string
        user_defined_type_schema:
          type: string
        user_defined_type_name:
          type: string
        is_insertable_into:
          type: string
        is_typed:
          type: string
        commit_action:
          type: string
        hasindexes:
          type: boolean
        hasrules:
          type: boolean
        hastriggers:
          type: boolean
        rowsecurity:
          type: boolean
        tablespace:
          type: string
      required:
        - table_catalog
        - table_schema
        - table_name
        - table_type
        - is_insertable_into
        - is_typed
        - hasindexes
        - hasrules
        - hastriggers
        - rowsecurity
      x-tags:
        - table
    ColumnDTO:
      description: Provides information about columns in database table
      type: object
      title: ColumnDTO
      x-tags:
        - column
      properties:
        column_name:
          type: string
          minLength: 1
        ordinal_position:
          type: number
        column_default:
          type: string
        is_nullable:
          type: string
          minLength: 1
        data_type:
          type: string
          minLength: 1
        character_maximum_length:
          type: number
        character_octet_length:
          type: number
        numeric_precision:
          type: number
        numeric_precision_radix:
          type: number
        numeric_scale:
          type: number
        datetime_precision:
          type: number
        interval_type:
          type: number
        interval_precision:
          type: number
        character_set_catalog:
          type: string
        character_set_schema:
          type: string
        character_set_name:
          type: string
        collation_catalog:
          type: string
        collation_schema:
          type: string
        collation_name:
          type: string
        domain_catalog:
          type: string
        domain_schema:
          type: string
        domain_name:
          type: string
        udt_catalog:
          type: string
          minLength: 1
        udt_schema:
          type: string
          minLength: 1
        udt_name:
          type: string
          minLength: 1
        scope_catalog:
          type: string
        scope_schema:
          type: string
        scope_name:
          type: string
        maximum_cardinality:
          type: number
        dtd_identifier:
          type: string
          minLength: 1
        is_self_referencing:
          type: string
          minLength: 1
        is_identity:
          type: string
          minLength: 1
        identity_generation:
          type: string
        identity_start:
          type: string
        identity_increment:
          type: string
        identity_maximum:
          type: string
        identity_minimum:
          type: string
        identity_cycle:
          type: string
          minLength: 1
        is_generated:
          type: string
          minLength: 1
        generation_expression:
          type: string
        is_updatable:
          type: string
          minLength: 1
paths:
  '/connections/{connectionID}':
    parameters:
      - schema:
          type: integer
          format: int64
          minimum: 1
        name: connectionID
        in: path
        description: Connection ID stored in database
        required: true
    get:
      summary: Get DB connection details by ID
      tags:
        - Connection
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConnectionDTO'
        '404':
          description: Connection not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiExceptionDTO'
      operationId: get-connections-connectionID
      description: Returns details about database connection specified by its ID
    put:
      summary: Update DB connection
      operationId: put-connections-connectionID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConnectionDTO'
        '201':
          description: Created - new DB connection is stored
          links:
            GetConnectionByConnectionID:
              operationId: get-connections-connectionID
              parameters:
                connectionID: $response.body#/id
              description: 'The `id` value returned in the response can be used as the `connectionID` parameter in `GET /connections/{connectionId}`.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConnectionDTO'
        '400':
          description: Bad Request - malformed request that DO NOT comfor with validations
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiExceptionDTO'
        '409':
          description: Conflict - Update voilates DB constraints
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiExceptionDTO'
      description: Updates DB connection specified by ID
      tags:
        - Connection
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConnectionDTO'
    delete:
      summary: Delete DB connection by ID
      operationId: delete-connections-connectionID
      responses:
        '204':
          description: OK
      description: Deletes DB connection specified by ID
      tags:
        - Connection
  /connections:
    post:
      summary: Create DB connection
      operationId: post-connections
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConnectionDTO'
          links:
            GetConnectionByConnectionID:
              operationId: get-connections-connectionID
              parameters:
                connectionID: $response.body#/id
              description: 'The `id` value returned in the response can be used as the `connectionID` parameter in `GET /connections/{connectionId}`.'
        '400':
          description: Bad Request - request validations has failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiExceptionDTO'
        '409':
          description: Conflict - creation of resource voilates DB constraints - ie name exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiExceptionDTO'
      description: Creates new DB connection
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConnectionDTO'
        description: DB Connection details
      tags:
        - Connection
  '/connections/{connectionId}/schemas':
    get:
      summary: List schemas
      tags:
        - schema
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SchemaDTO'
      operationId: get-schemas
      description: Lists all DB schemas with additional information
    parameters:
      - schema:
          type: string
        name: connectionId
        in: path
        required: true
  '/connections/{connectionId}/schemas/{schemaName}/tables':
    parameters:
      - schema:
          type: string
        name: schemaName
        in: path
        required: true
      - schema:
          type: string
        name: connectionId
        in: path
        required: true
    get:
      summary: List tables in schema
      tags:
        - table
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TableDTO'
      operationId: get-tables
      description: Lists all tables whitin a schema and provides additional information about each
  '/connections/{connectionId}/schemas/{schemaName}/tables/{tableName}/columns':
    parameters:
      - schema:
          type: string
        name: schemaName
        in: path
        required: true
      - schema:
          type: string
        name: tableName
        in: path
        required: true
      - schema:
          type: string
        name: connectionId
        in: path
        required: true
    get:
      summary: List columns
      tags:
        - column
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ColumnDTO'
      operationId: get-columns
      description: List all columns in database table and provides additional information about each
  '/connections/{connectionId}/schemas/{schemaName}/tables/{tableName}/data':
    parameters:
      - schema:
          type: string
        name: connectionId
        in: path
        required: true
      - schema:
          type: string
        name: schemaName
        in: path
        required: true
      - schema:
          type: string
        name: tableName
        in: path
        required: true
    get:
      summary: Preview data of table
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
              examples: {}
      operationId: get-preview
      description: Provides preview of stored data in table
tags:
  - name: Connection
  - name: column
  - name: table
  - name: schema
